pipeline {
    agent any

    stages {
        stage('Clonar Repositório') {
            steps {
                git 'https://seurepositorio.git'
            }
        }
        stage('Rodar Testes') {
            steps {
                sh 'pytest'
            }
        }
        stage('Build e Deploy') {
            steps {
                script {
                    // Construir as imagens Docker
                    def app = docker.build('meu_app', '.')
                    def db = docker.build('meu_db', '.')

                    // Rodar os containers
                    app.run('-p 5000:5000 -d')
                    db.run('-p 3306:3306 -d')
                }
            }
        }
    }
}
